### ISSUE TITLE
running the trpo_cartpole.py file with the argument adaptive_std = True gives the value error.

### ISSUE THREAD

**Issue by abhishm** [rllab/rllab#3] opened 2016-05-10 00:16 UTC
There is a parameter adaptive_std in the file https://github.com/rllab/rllab/blob/master/rllab/policies/gaussian_mlp_policy.py. The goal of this is to create a neural network architecture for learning std. I defined a policy with adaptive_std paramener true as in the following code and  run it. 
>>>
from rllab.algos.trpo import TRPO
from rllab.baselines.linear_feature_baseline import LinearFeatureBaseline
from rllab.envs.box2d.cartpole_env import CartpoleEnv
from rllab.envs.normalized_env import normalize
from rllab.policies.gaussian_mlp_policy import GaussianMLPPolicy
env = normalize(CartpoleEnv())
policy = GaussianMLPPolicy(
    env_spec=env.spec,
    # The neural network policy should have two hidden layers, each with 32 hidden units.
    hidden_sizes=(32, 32),
    adaptive_std=True
)
baseline = LinearFeatureBaseline(env_spec=env.spec)
algo = TRPO(
    env=env,
    policy=policy,
    baseline=baseline,
    batch_size=4000,
    max_path_length=100,
    n_itr=40,
    discount=0.99,
    step_size=0.01,
)
algo.train()

I got the following error.

2016-05-09 16:28:47.563510 PDT | Populating workers...
2016-05-09 16:28:47.675703 PDT | Populated
Traceback (most recent call last):
  File "/home/drl/rllab/examples/trpo_cartpole.py", line 28, in <module>
    algo.train()
  File "/home/drl/rllab/rllab/algos/batch_polopt.py", line 83, in train
    self.init_opt()
  File "/home/drl/rllab/rllab/algos/npo.py", line 69, in init_opt
    dist_info_vars = self.policy.dist_info_sym(obs_var, state_info_vars)
  File "/home/drl/rllab/rllab/policies/gaussian_mlp_policy.py", line 113, in dist_info_sym
    mean_var, log_std_var = L.get_output([self._l_mean, self._l_log_std], obs_var)
  File "/home/drl/anaconda2/envs/rllab/lib/python2.7/site-packages/lasagne/layers/helper.py", line 169, in get_output
    raise ValueError("get_output() was called with a single input "
ValueError: get_output() was called with a single input expression on a network with multiple input layers. Please call it with a dictionary of input expressions instead.

It will be really helpful if you can help me with the reason behind this error.

**Comment by dementrock** [comment] 2016-05-10 04:49
Hi @abhishm, this issue should be fixed on master now. The issue was caused by having a separate input layer when constructing the MLP for the standard deviation.

**Closed** 2016-05-10 04:48 UTC
